# Generated by Django 5.1.4 on 2025-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('emi', models.IntegerField()),
                ('tax', models.IntegerField()), 
                ('exp', models.IntegerField()),
            ],
        ),
    ]
