# Generated by Django 5.1.4 on 2025-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expenses_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='income_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
